env:
  es6: true
  node: true
extends:
  - '@bangbang93/recommended'
  - prettier
plugins:
  - '@typescript-eslint'
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
